# Generated by Django 3.0.5 on 2020-04-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('year', models.IntegerField()),
                ('cover', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=100)),
                ('image', models.TextField()),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
                ('authors', models.ManyToManyField(related_name='authors', to='api.Author')),
                ('genres', models.ManyToManyField(related_name='genres', to='api.Genre')),
            ],
        ),
    ]
